CREATE DATABASE INVENTARIOS
GO
USE INVENTARIOS
GO

CREATE TABLE ADMINISTRADOR 
    (
     NombreNetUserId INTEGER NOT NULL IDENTITY(1,1)
    )
GO

ALTER TABLE ADMINISTRADOR ADD CONSTRAINT ADMINISTRADOR_PK PRIMARY KEY CLUSTERED (NombreNetUserId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE ASPNETUSER 
    (
     NombreNetUserId INTEGER NOT NULL IDENTITY(1,1), 
     Nombres NVARCHAR (64) NOT NULL , 
     Apellidos NVARCHAR (64) NOT NULL , 
     FechaNacimiento DATETIME NOT NULL , 
     Direccion VARCHAR (64) NOT NULL , 
     Telefono VARCHAR (64) NOT NULL , 
     Correo VARCHAR (64) NOT NULL , 
     CorreoConfirmado BIT NOT NULL , 
     Contraseña VARCHAR (64) NOT NULL , 
     SelloDeSeguridad VARCHAR (64) NOT NULL , 
     ReclamarTelefono NVARCHAR (64) NOT NULL , 
     DosFactoresDisponibles NVARCHAR (64) NOT NULL , 
     FechCierre DATETIME NOT NULL , 
     FechaAbierta DATETIME NOT NULL , 
     AccesoDenegado BIT NOT NULL 
    )
GO

ALTER TABLE ASPNETUSER ADD CONSTRAINT ASPNETUSER_PK PRIMARY KEY CLUSTERED (NombreNetUserId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE ASPNETUSER_ASPNETUSERROLE 
    (
     ASPNETUSER_NombreNetUserId INTEGER NOT NULL IDENTITY(1,1), 
     ASPNETUSERROLE_AspNetRole INTEGER NOT NULL 
    )
GO

ALTER TABLE ASPNETUSER_ASPNETUSERROLE ADD CONSTRAINT ASPNETUSER_ASPNETUSERROLE_PK PRIMARY KEY CLUSTERED (ASPNETUSER_NombreNetUserId, ASPNETUSERROLE_AspNetRole)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE ASPNETUSERCLAIM 
    (
     Id INTEGER NOT NULL IDENTITY(1,1), 
     ClaimType NVARCHAR (64) NOT NULL , 
     ClaimValue DECIMAL (5,2) NOT NULL , 
     AspNetUserId INTEGER NOT NULL , 
     ASPNETUSER_NombreNetUserId INTEGER NOT NULL 
    )
GO

ALTER TABLE ASPNETUSERCLAIM ADD CONSTRAINT ASPNETUSERCLAIM_PK PRIMARY KEY CLUSTERED (Id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE ASPNETUSERLOGIN 
    (
     Id INTEGER NOT NULL IDENTITY(1,1), 
     LoginProvider NVARCHAR (64) NOT NULL , 
     ProviderKey DECIMAL (5,2) NOT NULL , 
     ASPNETUSER_NombreNetUserId INTEGER NOT NULL 
    )
GO

ALTER TABLE ASPNETUSERLOGIN ADD CONSTRAINT ASPNETUSERLOGIN_PK PRIMARY KEY CLUSTERED (Id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE ASPNETUSERROLE 
    (
     AspNetRole INTEGER NOT NULL , 
     Nombre NVARCHAR (64) NOT NULL 
    )
GO

ALTER TABLE ASPNETUSERROLE ADD CONSTRAINT ASPNETUSERROLE_PK PRIMARY KEY CLUSTERED (AspNetRole)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE CAJEROS 
    (
     NombreNetUserId INTEGER NOT NULL IDENTITY(1,1) 
    )
GO

ALTER TABLE CAJEROS ADD CONSTRAINT CAJEROS_PK PRIMARY KEY CLUSTERED (NombreNetUserId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE CATEGORIA 
    (
     CategoriaId INTEGER NOT NULL IDENTITY(1,1), 
     Nombre NVARCHAR (1024) NOT NULL , 
     Estado BIT NOT NULL 
    )
GO

ALTER TABLE CATEGORIA ADD CONSTRAINT CATEGORIA_PK PRIMARY KEY CLUSTERED (CategoriaId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE CLIENTES 
    (
     ClienteId INTEGER NOT NULL IDENTITY(1,1) 
    )
GO

ALTER TABLE CLIENTES ADD CONSTRAINT CLIENTES_PK PRIMARY KEY CLUSTERED (ClienteId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE DETALLEPEDIDO 
    (
     DetallePedidoId INTEGER NOT NULL IDENTITY(1,1), 
     Cantidad BIGINT NOT NULL , 
     PrecioUnitario BIGINT , 
     PEDIDO_PedidoId INTEGER NOT NULL 
    )
GO

ALTER TABLE DETALLEPEDIDO ADD CONSTRAINT DETALLEPEDIDO_PK PRIMARY KEY CLUSTERED (DetallePedidoId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE DETALLEPEDIDO_PRODUCTO 
    (
     DETALLEPEDIDO_DetallePedidoId INTEGER NOT NULL IDENTITY(1,1), 
     PRODUCTO_ProductoId INTEGER NOT NULL 
    )
GO

ALTER TABLE DETALLEPEDIDO_PRODUCTO ADD CONSTRAINT DETALLEPEDIDO_PRODUCTO_PK PRIMARY KEY CLUSTERED (DETALLEPEDIDO_DetallePedidoId, PRODUCTO_ProductoId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE EMPLEADOS 
    (
     NombreNetUserId INTEGER NOT NULL IDENTITY(1,1) 
    )
GO

ALTER TABLE EMPLEADOS ADD CONSTRAINT EMPLEADOS_PK PRIMARY KEY CLUSTERED (NombreNetUserId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE MARCA 
    (
     MarcaId INTEGER NOT NULL IDENTITY(1,1), 
     Nombre NVARCHAR (1024) NOT NULL , 
     Estado BIT NOT NULL 
    )
GO

ALTER TABLE MARCA ADD CONSTRAINT MARCA_PK PRIMARY KEY CLUSTERED (MarcaId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE PEDIDO 
    (
     PedidoId INTEGER NOT NULL IDENTITY(1,1), 
     Fecha DATE NOT NULL , 
     CLIENTES_ClienteId INTEGER NOT NULL , 
     ASPNETUSER_NombreNetUserId INTEGER NOT NULL 
    )
GO

ALTER TABLE PEDIDO ADD CONSTRAINT PEDIDO_PK PRIMARY KEY CLUSTERED (PedidoId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE PRECIO 
    (
     PrecioId INTEGER NOT NULL IDENTITY(1,1), 
     FechaIngreso DATE , 
     PrecioCompra MONEY NOT NULL , 
     PrecioVenta MONEY , 
     Descuento DECIMAL (5,2) , 
     PRODUCTO_ProductoId INTEGER NOT NULL 
    )
GO

ALTER TABLE PRECIO ADD CONSTRAINT PRECIO_PK PRIMARY KEY CLUSTERED (PrecioId, PRODUCTO_ProductoId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE PRODUCTO 
    (
     ProductoId INTEGER NOT NULL IDENTITY(1,1), 
     Nombre NVARCHAR (1024) NOT NULL , 
     Descripcion NVARCHAR (1024) , 
     Estado BIT NOT NULL , 
     UNIDADMEDIDA_UnidaMedidaId INTEGER NOT NULL , 
     MARCA_MarcaId INTEGER NOT NULL , 
     CodigoBarras NVARCHAR (24) , 
     Foto IMAGE , 
     SUBCATEGORIA_SubCategoriaId INTEGER NOT NULL 
    )
GO

ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_PK PRIMARY KEY CLUSTERED (ProductoId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE STATUSPEDIDO 
    (
     StatusId INTEGER NOT NULL IDENTITY(1,1), 
     Descripcion NVARCHAR (1024) , 
     PEDIDO_PedidoId INTEGER 
    )
GO

ALTER TABLE STATUSPEDIDO ADD CONSTRAINT STATUSPEDIDO_PK PRIMARY KEY CLUSTERED (StatusId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE STOCK 
    (
     StockId INTEGER NOT NULL IDENTITY(1,1), 
     FechaIngresoStock DATE NOT NULL , 
     CantidadStockIdeal INTEGER NOT NULL , 
     CantidadAlarma INTEGER NOT NULL , 
     CantidadStockReal INTEGER NOT NULL , 
     PRODUCTO_ProductoId INTEGER NOT NULL 
    )
GO

ALTER TABLE STOCK ADD CONSTRAINT STOCK_PK PRIMARY KEY CLUSTERED (StockId, PRODUCTO_ProductoId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE SUBCATEGORIA 
    (
     SubCategoriaId INTEGER NOT NULL IDENTITY(1,1), 
     Nombre NVARCHAR (1024) NOT NULL , 
     Estado BIT NOT NULL , 
     CATEGORIA_CategoriaId INTEGER NOT NULL 
    )
GO

ALTER TABLE SUBCATEGORIA ADD CONSTRAINT SUBCATEGORIA_PK PRIMARY KEY CLUSTERED (SubCategoriaId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE SUELDO 
    (
     SueldoId INTEGER NOT NULL IDENTITY(1,1), 
     FechaContrato DATETIME NOT NULL , 
     FechaFinalizacion DATETIME NOT NULL , 
     SueldoMensual FLOAT (5) NOT NULL , 
     ObjetoContrato NVARCHAR (64) NOT NULL , 
     SalarioTotal FLOAT (5) NOT NULL , 
     Estado BIT NOT NULL , 
     EMPLEADOS_NombreNetUserId INTEGER NOT NULL 
    )
GO

ALTER TABLE SUELDO ADD CONSTRAINT SUELDO_PK PRIMARY KEY CLUSTERED (SueldoId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE TIPOTRANSACCION 
    (
     TransaccionId INTEGER NOT NULL IDENTITY(1,1), 
     Descripcion NVARCHAR (1024) 
    )
GO

ALTER TABLE TIPOTRANSACCION ADD CONSTRAINT TIPOTRANSACCION_PK PRIMARY KEY CLUSTERED (TransaccionId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE TRANSACCION 
    (
     TransaccionId INTEGER NOT NULL IDENTITY(1,1), 
     FechaTransaccion DATETIME NOT NULL , 
     CantidadProducto FLOAT (10) NOT NULL , 
     OtrosDeatalles NVARCHAR (1024) , 
     PRODUCTO_ProductoId INTEGER NOT NULL , 
     TIPOTRANSACCION_TransaccionId INTEGER NOT NULL 
    )
GO

ALTER TABLE TRANSACCION ADD CONSTRAINT TRANSACCION_PK PRIMARY KEY CLUSTERED (TransaccionId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE TURNO 
    (
     TurnoId INTEGER NOT NULL IDENTITY(1,1), 
     FechaTurno DATE NOT NULL , 
     HoraIngreso NUMERIC (5,2) NOT NULL , 
     HoraIngreso_1 NUMERIC (5,2) NOT NULL , 
     Estado BIT NOT NULL , 
     AspNetUserId INTEGER NOT NULL , 
     EMPLEADOS_NombreNetUserId INTEGER NOT NULL 
    )
GO

ALTER TABLE TURNO ADD CONSTRAINT TURNO_PK PRIMARY KEY CLUSTERED (TurnoId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE UNIDADMEDIDA 
    (
     UnidaMedidaId INTEGER NOT NULL IDENTITY(1,1), 
     Nombre NVARCHAR (1024) NOT NULL , 
     Estado BIT 
    )
GO

ALTER TABLE UNIDADMEDIDA ADD CONSTRAINT UNIDADMEDIDA_PK PRIMARY KEY CLUSTERED (UnidaMedidaId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE ADMINISTRADOR 
    ADD CONSTRAINT ADMINISTRADOR_EMPLEADOS_FK FOREIGN KEY 
    ( 
     NombreNetUserId
    ) 
    REFERENCES EMPLEADOS 
    ( 
     NombreNetUserId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ASPNETUSER_ASPNETUSERROLE 
    ADD CONSTRAINT ASPNETUSER_ASPNETUSERROLE_ASPNETUSER_FK FOREIGN KEY 
    ( 
     ASPNETUSER_NombreNetUserId
    ) 
    REFERENCES ASPNETUSER 
    ( 
     NombreNetUserId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ASPNETUSER_ASPNETUSERROLE 
    ADD CONSTRAINT ASPNETUSER_ASPNETUSERROLE_ASPNETUSERROLE_FK FOREIGN KEY 
    ( 
     ASPNETUSERROLE_AspNetRole
    ) 
    REFERENCES ASPNETUSERROLE 
    ( 
     AspNetRole 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ASPNETUSERCLAIM 
    ADD CONSTRAINT ASPNETUSERCLAIM_ASPNETUSER_FK FOREIGN KEY 
    ( 
     ASPNETUSER_NombreNetUserId
    ) 
    REFERENCES ASPNETUSER 
    ( 
     NombreNetUserId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ASPNETUSERLOGIN 
    ADD CONSTRAINT ASPNETUSERLOGIN_ASPNETUSER_FK FOREIGN KEY 
    ( 
     ASPNETUSER_NombreNetUserId
    ) 
    REFERENCES ASPNETUSER 
    ( 
     NombreNetUserId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE CAJEROS 
    ADD CONSTRAINT CAJEROS_EMPLEADOS_FK FOREIGN KEY 
    ( 
     NombreNetUserId
    ) 
    REFERENCES EMPLEADOS 
    ( 
     NombreNetUserId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE DETALLEPEDIDO 
    ADD CONSTRAINT DETALLEPEDIDO_PEDIDO_FK FOREIGN KEY 
    ( 
     PEDIDO_PedidoId
    ) 
    REFERENCES PEDIDO 
    ( 
     PedidoId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE DETALLEPEDIDO_PRODUCTO 
    ADD CONSTRAINT DETALLEPEDIDO_PRODUCTO_DETALLEPEDIDO_FK FOREIGN KEY 
    ( 
     DETALLEPEDIDO_DetallePedidoId
    ) 
    REFERENCES DETALLEPEDIDO 
    ( 
     DetallePedidoId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE DETALLEPEDIDO_PRODUCTO 
    ADD CONSTRAINT DETALLEPEDIDO_PRODUCTO_PRODUCTO_FK FOREIGN KEY 
    ( 
     PRODUCTO_ProductoId
    ) 
    REFERENCES PRODUCTO 
    ( 
     ProductoId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE EMPLEADOS 
    ADD CONSTRAINT EMPLEADOS_ASPNETUSER_FK FOREIGN KEY 
    ( 
     NombreNetUserId
    ) 
    REFERENCES ASPNETUSER 
    ( 
     NombreNetUserId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE PEDIDO 
    ADD CONSTRAINT PEDIDO_ASPNETUSER_FK FOREIGN KEY 
    ( 
     ASPNETUSER_NombreNetUserId
    ) 
    REFERENCES ASPNETUSER 
    ( 
     NombreNetUserId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE PEDIDO 
    ADD CONSTRAINT PEDIDO_CLIENTES_FK FOREIGN KEY 
    ( 
     CLIENTES_ClienteId
    ) 
    REFERENCES CLIENTES 
    ( 
     ClienteId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE PRECIO 
    ADD CONSTRAINT PRECIO_PRODUCTO_FK FOREIGN KEY 
    ( 
     PRODUCTO_ProductoId
    ) 
    REFERENCES PRODUCTO 
    ( 
     ProductoId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE PRODUCTO 
    ADD CONSTRAINT PRODUCTO_MARCA_FK FOREIGN KEY 
    ( 
     MARCA_MarcaId
    ) 
    REFERENCES MARCA 
    ( 
     MarcaId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE PRODUCTO 
    ADD CONSTRAINT PRODUCTO_SUBCATEGORIA_FK FOREIGN KEY 
    ( 
     SUBCATEGORIA_SubCategoriaId
    ) 
    REFERENCES SUBCATEGORIA 
    ( 
     SubCategoriaId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE PRODUCTO 
    ADD CONSTRAINT PRODUCTO_UNIDADMEDIDA_FK FOREIGN KEY 
    ( 
     UNIDADMEDIDA_UnidaMedidaId
    ) 
    REFERENCES UNIDADMEDIDA 
    ( 
     UnidaMedidaId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE STATUSPEDIDO 
    ADD CONSTRAINT STATUSPEDIDO_PEDIDO_FK FOREIGN KEY 
    ( 
     PEDIDO_PedidoId
    ) 
    REFERENCES PEDIDO 
    ( 
     PedidoId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE STOCK 
    ADD CONSTRAINT STOCK_PRODUCTO_FK FOREIGN KEY 
    ( 
     PRODUCTO_ProductoId
    ) 
    REFERENCES PRODUCTO 
    ( 
     ProductoId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SUBCATEGORIA 
    ADD CONSTRAINT SUBCATEGORIA_CATEGORIA_FK FOREIGN KEY 
    ( 
     CATEGORIA_CategoriaId
    ) 
    REFERENCES CATEGORIA 
    ( 
     CategoriaId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SUELDO 
    ADD CONSTRAINT SUELDO_EMPLEADOS_FK FOREIGN KEY 
    ( 
     EMPLEADOS_NombreNetUserId
    ) 
    REFERENCES EMPLEADOS 
    ( 
     NombreNetUserId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE TRANSACCION 
    ADD CONSTRAINT TRANSACCION_PRODUCTO_FK FOREIGN KEY 
    ( 
     PRODUCTO_ProductoId
    ) 
    REFERENCES PRODUCTO 
    ( 
     ProductoId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE TRANSACCION 
    ADD CONSTRAINT TRANSACCION_TIPOTRANSACCION_FK FOREIGN KEY 
    ( 
     TIPOTRANSACCION_TransaccionId
    ) 
    REFERENCES TIPOTRANSACCION 
    ( 
     TransaccionId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE TURNO 
    ADD CONSTRAINT TURNO_EMPLEADOS_FK FOREIGN KEY 
    ( 
     EMPLEADOS_NombreNetUserId
    ) 
    REFERENCES EMPLEADOS 
    ( 
     NombreNetUserId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO