/*QUERY*/


 /*Select*/
 SELECT * FROM PERSONA_ROL;

 SELECT DESC_CATEGORIA FROM CATEGORIA;

 SELECT PRI_NOMBRE_PERSONA,SEG_APELLIDO_PERSONA,CORREO_PERSONA FROM PERSONA WHERE TIPDOC_ID ='C.C';

 SELECT * FROM PERSONA WHERE TIPDOC_ID = 'NIT';

 SELECT NOMBRE_EMPRESA,TEL_CONTACTO FROM EMPRESA;

 /*Update */
 UPDATE PERSONA SET
 PRI_NOMBRE_PERSONA='SEBASTIAN' WHERE PRI_NOMBRE_PERSONA='SEBAS';

 UPDATE PRODUCTO SET
 VALOR_VENTAUNI=12.78 WHERE CATEGORIA_PRODUCTO =12;

 UPDATE ROLES SET
 DESCRIP_ROL='VENDEDOR' WHERE DESCRIP_ROL='EMPLEADO';

 UPDATE PERSONA 
 SET CEL_PERSONA=replace(CEL_PERSONA,'3440923','5673892')
 WHERE CEL_PERSONA LIKE '%3440923%';

 UPDATE PROVEEDOR
 SET SEG_APELLIDO_PROVEEDOR = 'DE LA CRUZ'
 WHERE PRI_NOMBRE_PROVEEDOR='CAMILO' AND SEG_NOMBRE_PROVEEDOR = 'ANDRES' AND PRI_APELLIDO_PROVEEDOR = 'TORRES';

 UPDATE PROVEEDOR
 SET SEG_APELLIDO_PROVEEDOR = 'RODRIGUEZ'
 WHERE PRI_NOMBRE_PROVEEDOR='CAMILO' AND SEG_NOMBRE_PROVEEDOR = 'ANDRES' OR SEG_NOMBRE_PROVEEDOR = 'ANTONIO';


 /*Delete*/
 DELETE FROM CLIENTE;

 DELETE FROM CLIENTE WHERE CLIENTE_TDOC='C.E';

 DELETE FROM PRODUCTO WHERE MARCA_PRODUCTO='10';

 /*ORDER BY*/
 SELECT * FROM PRODUCTO ORDER BY CANTIDAD_EXIST DESC;
 SELECT * FROM PRODUCTO ORDER BY VALOR_VENTAUNI ASC;
 SELECT * FROM PERSONA ORDER BY PRI_APELLIDO_PERSONA DESC;
 SELECT ID_FACTURA_ID,CANT_PRODUCTO FROM FACT_PRODUCTO ORDER BY ID_FACTURA_ID ASC;
 SELECT * FROM FACT_VENTA ORDER BY ID_FACTURA_VENTA ASC,ID_CLIENTE DESC;

/*GROUP BY*/
 SELECT SEG_APELLIDO_PERSONA FROM PERSONA GROUP BY SEG_APELLIDO_PERSONA;
 SELECT SEG_NOMBRE_PERSONA FROM PERSONA GROUP BY SEG_NOMBRE_PERSONA;
 SELECT COUNT(PROVEEDOR_ID), PRI_APELLIDO_PROVEEDOR FROM PROVEEDOR GROUP BY PRI_APELLIDO_PROVEEDOR;

 /*COUNT/MAX/MIN*/

 SELECT COUNT(PERSONA_ID) FROM PERSONA;
 SELECT MAX(CANTIDAD_MAX) FROM PRODUCTO;
 SELECT MIN(CANTIDAD_MAX) FROM PRODUCTO;

 /*INNER JOIN*/
 SELECT * FROM MARCA INNER JOIN PRODUCTO ON MARCA.MARCA_ID=PRODUCTO.MARCA_PRODUCTO;

 SELECT * FROM FACT_PRODUCTO JOIN FACTURA ON FACT_PRODUCTO.ID_FACTURA_ID = FACTURA.FACTURA_ID;

 SELECT PROVEEDOR.PROVEEDOR_ID,EMPRESA.EMPRESA_ID,PROVEEDOR.SEG_APELLIDO_PROVEEDOR 
 FROM PROVEEDOR INNER JOIN EMPRESA 
 ON PROVEEDOR.EMPRESA_PROVEEDOR=EMPRESA.EMPRESA_ID;

 SELECT FACT_COMPRA.ID_FACT_COMPRA, FACTURA.FECHA_FACTURA,factura.TOTAL_FAC 
 FROM FACT_COMPRA INNER JOIN FACTURA 
 ON FACT_COMPRA.ID_FACT_COMPRA = FACTURA.FACTURA_ID;

SELECT FACTURA.FACTURA_ID,FACTURA.FECHA_FACTURA,FACT_COMPRA.ID_EMPLEADO,PROVEEDOR.PROVEEDOR_ID 
FROM ((FACT_COMPRA 
INNER JOIN FACTURA ON FACT_COMPRA.ID_FACT_COMPRA = FACTURA.FACTURA_ID) 
INNER JOIN PROVEEDOR ON FACT_COMPRA.ID_PROVEEDOR = PROVEEDOR.PROVEEDOR_ID);

 /*LEFT JOIN*/

 SELECT PERSONA.PRI_NOMBRE_PERSONA,ROLES.DESCRIP_ROL
 FROM PERSONA 
 LEFT JOIN ROLES ON PERSONA.PERSONA_ID = ROLES.ROL_ID;

 SELECT PRI_NOMBRE_PERSONA,CEL_PERSONA,DIREC_PERSONA,TIPDOC_ID 
 FROM PERSONA LEFT JOIN TIPODOC ON PERSONA.TIPDOC_ID=TIPODOC.TIPO_DOC;

 SELECT VALOR_PRODUCTO, ID_PRODUCTO_ID,ID_FACTURA_ID 
 FROM FACT_PRODUCTO LEFT JOIN FACTURA ON FACT_PRODUCTO.ID_FACTURA_ID=FACTURA.FACTURA_ID;

 SELECT MARCA.DESCRIP_MARCA,PRODUCTO.DESCRIP_PRODUCTO,PRODUCTO.FECHA_CADUCIDAD 
 FROM MARCA LEFT JOIN PRODUCTO ON MARCA.MARCA_ID = PRODUCTO.MARCA_PRODUCTO;

 /*RIGHT JOIN*/


SELECT MARCA.DESCRIP_MARCA,PRODUCTO.DESCRIP_PRODUCTO,PRODUCTO.FECHA_CADUCIDAD 
FROM MARCA RIGHT JOIN PRODUCTO ON MARCA.MARCA_ID = PRODUCTO.MARCA_PRODUCTO;

 SELECT FACTURA.FACTURA_ID, COUNT(FACT_PRODUCTO.CANT_PRODUCTO) 
 AS 'Cantidad Productos' FROM FACTURA RIGHT JOIN FACT_PRODUCTO 
 ON FACTURA.FACTURA_ID=FACT_PRODUCTO.ID_FACTURA_ID;

 SELECT CATEGORIA.DESC_CATEGORIA as 'Categoria',
 PRODUCTO.DESCRIP_PRODUCTO as 'Producto' FROM CATEGORIA
 JOIN PRODUCTO ON CATEGORIA.CATEGORIA_ID = PRODUCTO.CATEGORIA_PRODUCTO